// src/views/DashboardCustomer.vue
<template>
  <div class="dashboard-container">
    <h1>Dashboard użytkownika</h1>
    <div class="menu">
        <li><router-link to="/books">Książki</router-link></li>
        <li @click="logout">Wyloguj</li>
    </div>
    <div v-if="loading" class="loading">Ładowanie...</div>
    <div v-else-if="error" class="error">{{ error }}</div>
    <div v-else>
      <h2>Witaj, {{ dashboardData.username }}</h2>
      
      <section class="section">
        <h3>Wypożyczone książki</h3>
        <ul>
          <li v-for="book in dashboardData.rented_books" :key="book.id">
            {{ book.book_title }} - {{ book.book_author }} ({{ book.due_date }})
          </li>
        </ul>
      </section>
      
      <section class="section">
        <h3>Historia wypożyczeń</h3>
        <ul>
          <li v-for="book in dashboardData.rented_books_old" :key="book.id">
            {{ book.book_title }} - {{ book.book_author }} (Zwrócono: {{ book.return_date }})
          </li>
        </ul>
      </section>
      
      <section class="section">
        <h3>Powiadomienia</h3>
        <ul>
          <li v-for="notification in dashboardData.notifications" :key="notification.id">
            {{ notification.message }}
          </li>
        </ul>
      </section>
      
      <section class="section">
        <h3>Twoje opinie</h3>
        <ul>
          <li v-for="opinion in dashboardData.opinions" :key="opinion.id">
            {{ opinion.book_title }} - Ocena: {{ opinion.rate }}<br>
            {{ opinion.comment }}
          </li>
        </ul>
      </section>
      
      <section class="section">
        <h3>Rekomendacje AI</h3>
        <ul>
          <li v-for="(recommendation, index) in dashboardData.ai_recommendations" :key="index">
            {{ recommendation }}
          </li>
        </ul>
      </section>
      
      <section class="section">
        <h3>Odznaki</h3>
        <ul>
          <li v-if="dashboardData.badges.first_book">Pierwsza książka wypożyczona</li>
          <li v-if="dashboardData.badges.ten_books">Wypożyczono 10 książek</li>
          <li v-if="dashboardData.badges.twenty_books">Wypożyczono 20 książek</li>
          <li v-if="dashboardData.badges.hundred_books">Wypożyczono 100 książek</li>
          <li v-if="dashboardData.badges.three_categories">Wypożyczono książki z 3 różnych kategorii</li>
        </ul>
      </section>
    </div>
  </div>
</template>

<script>
import authService from '@/helpers/auth'

export default {
  data() {
    return {
      dashboardData: null,
      loading: true,
      error: null,
    }
  },
  async created() {
    try {
      const response = await authService.getDashboardCustomer()
      this.dashboardData = response.data
    } catch (err) {
      this.error = err
      this.$router.push('/dashboard/employee/')
    } finally {
      this.loading = false
    }
  },
  methods: {
    toggleDropdown() {
      this.dropdownOpen = !this.dropdownOpen
    },
    toggleSection(index) {
      this.expanded[index] = !this.expanded[index]
    },
    formatItem(item) {
      if (item.book_title) return `${item.book_title} - ${item.book_author || ''} (${item.due_date || item.return_date || ''})`
      return item.message
    },
    logout() {
      authService.logout()
      this.$router.push('/login')
    }
  }
}
</script>

<style scoped>
.dashboard-container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: 'Roboto', 'Open Sans', sans-serif;
  color: #333;
}

h1 {
  color: #2c3e50;
  border-bottom: 2px solid #3498db;
  padding-bottom: 10px;
  margin-bottom: 30px;
}

h2 {
  color: #2980b9;
  margin-bottom: 20px;
}

h3 {
  color: #3498db;
  margin-bottom: 15px;
  border-left: 3px solid #3498db;
  padding-left: 10px;
}

.section {
  background-color: #fff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  padding: 20px;
  margin-bottom: 25px;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  padding: 12px 0;
  border-bottom: 1px solid #eee;
}

li:last-child {
  border-bottom: none;
}

.loading {
  text-align: center;
  padding: 30px;
  font-size: 18px;
  color: #7f8c8d;
}

.error {
  background-color: #f8d7da;
  color: #721c24;
  padding: 15px;
  border-radius: 5px;
  margin-bottom: 20px;
}

/* Dodatkowe style dla odznaki */
.section:nth-child(7) li {
  position: relative;
  padding-left: 30px;
}

.section:nth-child(7) li:before {
  content: "🏆";
  position: absolute;
  left: 0;
  top: 10px;
}

/* Style dla powiadomień */
.section:nth-child(4) li {
  background-color: #f9f9f9;
  padding: 12px 15px;
  border-radius: 5px;
  border-left: 3px solid #3498db;
  margin-bottom: 8px;
}

/* Style dla gwiazdek przy opiniach */
.section:nth-child(5) li {
  padding-bottom: 18px;
}

/* Style dla rekomendacji */
.section:nth-child(6) li {
  background-color: #ebf5fb;
  padding: 12px 15px;
  border-radius: 5px;
  border-left: 3px solid #2ecc71;
  margin-bottom: 8px;
}
.menu {
  position: relative;
  display: inline-block;
}

.menu-button {
  background: #0073e6;
  color: white;
  border: none;
  padding: 10px 15px;
  font-size: 16px;
  border-radius: 5px;
  cursor: pointer;
  transition: background 0.3s ease;
}

.menu-button:hover {
  background: #005bb5;
}

.dropdown {
  position: absolute;
  right: 0;
  top: 100%;
  background: white;
  border: 1px solid #ccc;
  border-radius: 5px;
  box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
  list-style: none;
  padding: 10px 0;
  margin: 5px 0 0;
  width: 150px;
  z-index: 10;
  animation: fadeIn 0.3s ease-in-out;
}

.dropdown li {
  padding: 10px;
  text-align: center;
  cursor: pointer;
  transition: background 0.3s ease;
}

.dropdown li:hover {
  background: #f1f1f1;
}

.dropdown a {
  text-decoration: none;
  color: black;
  display: block;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

/* Responsywność */
@media (max-width: 600px) {
  .dropdown {
    width: 100%;
    text-align: left;
  }
}



/* Responsywność */
@media (max-width: 768px) {
  .dashboard-container {
    padding: 10px;
  }
  
  .section {
    padding: 15px;
  }
}
</style>

// src/screens/DashboardCustomer.jsx
// src/screens/DashboardCustomer.jsx
import React, { useEffect, useState } from 'react';
import { dashboardApi } from '../services/apiServices';
import { useNavigate } from 'react-router-dom';

const DashboardCustomer = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [menuOpen, setMenuOpen] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    (async () => {
      try {
        const token = localStorage.getItem('accessToken');
        if (!token) {
          alert('Brak tokena, zaloguj się ponownie');
          navigate('/');
          return;
        }
        const resp = await dashboardApi.getCustomerDashboard();
        setData(resp.data);
      } catch {
        navigate('/dashboard-employee');
      } finally {
        setLoading(false);
      }
    })();
  }, [navigate]);

  if (loading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <span>Ładowanie…</span>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="p-4 text-center italic text-gray-600">
        Błąd ładowania danych
      </div>
    );
  }

  const formatDate = (d) => new Date(d).toLocaleDateString();
  const daysRemaining = (d) => {
    const diff = Math.ceil((new Date(d).getTime() - Date.now()) / (1000 * 60 * 60 * 24));
    if (diff < 0) return `${-diff} dni opóźnienia`;
    if (diff === 0) return 'Termin dziś';
    return `${diff} dni`;
  };

  return (
    <div className="min-h-screen bg-gray-100">
      {/* HEADER */}
      <header className="bg-blue-800 text-white flex items-center p-4">
        <button
          onClick={() => setMenuOpen((o) => !o)}
          className="mr-4 focus:outline-none"
        >
          <span className="block w-6 h-0.5 bg-white mb-1" />
          <span className="block w-6 h-0.5 bg-white mb-1" />
          <span className="block w-6 h-0.5 bg-white" />
        </button>
        <h1 className="text-2xl font-bold">Profil czytelnika</h1>
      </header>

      {/* SIDE MENU */}
      <aside
        className={
          'fixed top-0 left-0 h-full w-64 bg-white shadow transform transition-transform ' +
          (menuOpen ? 'translate-x-0' : '-translate-x-full')
        }
      >
        <div className="p-4 bg-blue-800 text-white">Menu</div>
        <nav className="p-4 space-y-2">
          <button
            onClick={() => {
              navigate('/dashboard-customer');
              setMenuOpen(false);
            }}
            className="block w-full text-left"
          >
            Strona główna
          </button>
          <button
            onClick={() => {
              navigate('/books');
              setMenuOpen(false);
            }}
            className="block w-full text-left"
          >
            Książki
          </button>
          <button
            onClick={() => {
              navigate('/logout');
              setMenuOpen(false);
            }}
            className="block w-full text-left"
          >
            Wyloguj się
          </button>
        </nav>
      </aside>
      {menuOpen && (
        <div
          onClick={() => setMenuOpen(false)}
          className="fixed inset-0 bg-black opacity-50"
        />
      )}

      {/* MAIN CONTENT */}
      <main className="p-4">
        {/* Welcome */}
        <section className="bg-white p-6 mb-4 shadow">
          <h2 className="text-xl">Witaj, {data.username}!</h2>
        </section>

        {/* Achievements */}
        <section className="bg-white p-6 mb-4 shadow">
          <h3 className="text-lg mb-2">🏆 Osiągnięcia</h3>
          <div className="flex flex-wrap gap-2">
            {data.badges.first_book && (
              <span className="px-3 py-1 bg-blue-800 text-white rounded-full">
                Pierwsza książka
              </span>
            )}
            {data.badges.ten_books && (
              <span className="px-3 py-1 bg-blue-800 text-white rounded-full">
                10 książek
              </span>
            )}
            {data.badges.twenty_books && (
              <span className="px-3 py-1 bg-blue-800 text-white rounded-full">
                20 książek
              </span>
            )}
            {data.badges.hundred_books && (
              <span className="px-3 py-1 bg-blue-800 text-white rounded-full">
                100 książek
              </span>
            )}
            {data.badges.three_categories && (
              <span className="px-3 py-1 bg-blue-800 text-white rounded-full">
                3 kategorie
              </span>
            )}
          </div>
        </section>

        {/* Stats */}
        <section className="bg-white p-6 mb-4 shadow flex justify-around">
          <div className="text-center">
            <div className="text-2xl font-bold">{data.all_my_rents}</div>
            <div>Przeczytane</div>
          </div>
          <div className="text-center">
            <div className="text-2xl font-bold">
              {data.average_user_rents.toFixed(1)}
            </div>
            <div>Śr. wypożyczeń</div>
          </div>
        </section>

        {/* Favorite Categories */}
        <section className="bg-white p-6 mb-4 shadow">
          <h3 className="text-lg mb-2">📚 Ulubione kategorie</h3>
          <div className="flex overflow-x-auto gap-4">
            {data.books_in_categories.length ? (
              data.books_in_categories.map((c, i) => (
                <div
                  key={i}
                  className="min-w-[140px] p-4 border rounded"
                >
                  <div className="font-bold">
                    {c.book_copy__book__category__name}
                  </div>
                  <div>{c.count} książki</div>
                </div>
              ))
            ) : (
              <div className="italic">Brak ulubionych kategorii</div>
            )}
          </div>
        </section>

        {/* Currently Rented */}
        <section className="mb-4">
          <h3 className="text-lg mb-2">📚 Aktualnie wypożyczone</h3>
          {data.rented_books.length ? (
            data.rented_books.map((b) => (
              <div
                key={b.id}
                className="bg-white p-4 mb-3 rounded shadow border-l-4 border-blue-800 cursor-pointer"
                onClick={() => navigate(`/return-book/${b.rentalId}`)}
              >
                <div className="flex justify-between">
                  <div className="font-bold">{b.book_title}</div>
                </div>
                <div className="text-sm text-gray-600">
                  by {b.book_author}
                </div>
                <div
                  className={
                    'inline-block mt-2 px-2 py-1 text-xs rounded text-white ' +
                    (b.is_extended ? 'bg-gray-600' : 'bg-blue-800')
                  }
                >
                  {b.is_extended ? 'Przedłużony' : daysRemaining(b.due_date)}
                </div>
                <div className="text-xs text-gray-600 mt-1">
                  {formatDate(b.rental_date)} – {formatDate(b.due_date)}
                </div>
              </div>
            ))
          ) : (
            <div className="italic">Brak aktualnych wypożyczeń</div>
          )}
        </section>

                {/* Historia wypożyczeń */}
                <section className="bg-white p-6 mb-4 shadow">
          <h3 className="text-lg mb-2">📘 Historia wypożyczania</h3>
          {data.rented_books_old && data.rented_books_old.length > 0 ? (
            data.rented_books_old.map((item, index) => (
              <div 
                key={item.id ? item.id.toString() : `history-${index}`} 
                className="p-4 mb-3 border-b"
              >
                <div className="font-bold">{item.book_title}</div>
                <div className="text-sm text-gray-600">by {item.book_author}</div>
                <div className="text-xs text-gray-600 mt-1">
                  Zwrócone: {formatDate(item.return_date)}
                </div>
              </div>
            ))
          ) : (
            <div className="italic">Brak historii wypożyczania</div>
          )}
        </section>

        {/* Powiadomienia */}
        <section className="bg-white p-6 mb-4 shadow">
          <h3 className="text-lg mb-2">🔔 Powiadomienia</h3>
          {data.notifications && data.notifications.length > 0 ? (
            data.notifications.map((item, index) => (
              <div 
                key={item.id ? item.id.toString() : `notification-${index}`} 
                className="p-4 mb-3 border-b"
              >
                <div className="text-sm">{item.message}</div>
                <div className="text-xs text-gray-600 mt-1">
                  {formatDate(item.created_at?.split('T')[0])}
                </div>
              </div>
            ))
          ) : (
            <div className="italic">Brak powiadomień</div>
          )}
        </section>

        {/* Rekomendacje */}
        <section className="bg-white p-6 mb-4 shadow">
          <h3 className="text-lg mb-2">📚 Polecane</h3>
          {data.ai_recommendations && data.ai_recommendations.length > 0 ? (
            data.ai_recommendations.map((item, index) => (
              <div 
                key={`recommendation-${index}`} 
                className="p-4 mb-3 border-b"
              >
                <div className="text-sm">{item}</div>
              </div>
            ))
          ) : (
            <div className="italic">Brak polecanych</div>
          )}
        </section>

        {/* Oceny */}
        <section className="bg-white p-6 mb-4 shadow">
          <h3 className="text-lg mb-2">⭐ Moje oceny książek</h3>
          {data.opinions && data.opinions.length > 0 ? (
            data.opinions.map((item, index) => (
              <div 
                key={item.id ? item.id.toString() : `review-${index}`} 
                className="p-4 mb-3 border-b"
              >
                <div className="flex justify-between">
                  <div className="font-bold">{item.book_title}</div>
                  <div>
                    {Array(item.rate).fill('⭐').join('')}
                  </div>
                </div>
                <div className="text-sm italic mt-2">"{item.comment}"</div>
                <div className="text-xs text-gray-600 mt-1">
                  {formatDate(item.created_at)}
                </div>
              </div>
            ))
          ) : (
            <div className="italic">Brak ocen</div>
          )}
        </section>
      </main>
    </div>
  );
};

export default DashboardCustomer;
